language: java
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "notification-system"
    token:
       secure: "Kl3V7G/WxV9nT6Z9XIe2CPhClNafGrNIACZ6wDGWgnjE1RRHDGIWEIrBACarDjjA5OuKRGvZZc40n+JaUTYSNh7KaBgp/WuxYqCGfBvUIYOPX3GshP76obvCwNbUKxFgJF/rTCSOeR/EPwiH+uOIRE7im6OOYN04MXLm8sJtbdwujCIKVTSgnszQo/9ceFmvccEilxfGrHh3zHmJlrJtjvPlJKfOFj/TAgEhmA5lxKqpdLmGih7TejnnqKtPdNZY2fk6Uu81f52rIRkSOv0Ed03n47f9EqNRZIU3XFgcq/uGxirOGE9Xn+nirCGFlZtG08G078s/WWLCepm4yloJ4cd2CoPexIbj5tOm4dBCFw8tVSa86EPGhJaN4dAtpGE539S6YmzjdIijeIrYjpL0jZXGaZO3oh8Wi8iql/vSihRaK2z1ZGLafqwkMlHw9DblVxMsZcGfDWCMsXMcFIV9gdZX76axdYEB4zXcuYf3OBIUZI7SDhXwBnF+mfDcBudbb/uaEHhYH8sUoO5JtHRfKWeodkl0LqhbcIVJBnq8sLVOg46OngmBG5G/gMEb4fjq0zoHirF5PvDb0XYsjK3PNLToOvKMEDXheCeG4fiBdHwU8fy0OXdg/ULPRlU5mLsbD+uR6n/XUEosNhwi3BkCYmpPnKpnROw/E4ezhGTRpTo="

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
services:
  - docker

after_success:
- if tag IS present; then
   docker login -u $DOCKER_USER -p $DOCKER_PASS
   docker build -t $IMAGE_TAG .
   docker push $IMAGE_TAG
  fi

